### ISSUE TITLE
Adding complex alerts

### ISSUE THREAD

**Issue by nimrodshn** [MohawkTSDB/mohawk#78]
Adding complex alerting i.e.
```
Alert #1 :  "free memory too low"
Alert #2: "cpu_usage too low"
Alert #3: Alert #1 && Alert #2 are on.
```

**Comment by nimrodshn** [comment]
@yaacov How should a yaml file look like when we have complex alerting? 
i.e. say I have the following alerts defined:
```
backend: "memory"
port: 8085
alerts:
- id: "free_memory is low"
  metric: "free_memory"
  from: 2000
  to: 2100
  type: 0
- id: "cpu is high"
  metric: "cpu_usage"
  to: 0.9
  type: 1
```
What should `Alert 3 = Alert 1 &&  Alert 2` look like?
